<?php
require_once ZOLO_DIR_PATH . 'includes/Blocks/PostGrid.php';
require_once ZOLO_DIR_PATH . 'includes/Blocks/PostList.php';

return apply_filters('zolo_blocks_list_data', [
    'container' => [
        'name' => 'container',
        'title' => __('Container', 'zoloblocks'),
        'categories' => ['others'],
        'status' => true,
        'demo' => 'https://zoloblocks.com',
        'video' => 'https://youtu.be/HPEVm1xGT3I?list=PLFnvpmjcONzLJMQiRFpLAxHsz-RSmZstT',
    ],
    'accordion' => [
        'name' => 'accordion',
        'title' => __('Accordion', 'zoloblocks'),
        'categories' => ['others'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/accordion',
        'video' => 'https://www.youtube.com/watch?v=LQO2oZ7Sg14&list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'accordion-child' => [
        'name' => 'accordion-child',
        'title' => __('Accordion Child', 'zoloblocks'),
        'categories' => ['others'],
        'status' => true,
        'is_child' => true,
    ],
    'advanced-button' => [
        'name' => 'advanced-button',
        'title' => __('Advanced Button', 'zoloblocks'),
        'categories' => ['others'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/advanced-button',
        'video' => 'https://www.youtube.com/watch?v=KFKnRqxOKEo&list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'advanced-heading' => [
        'name' => 'advanced-heading',
        'title' => __('Advanced Heading', 'zoloblocks'),
        'categories' => ['others'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/advanced-heading',
        'video' => 'https://www.youtube.com/watch?v=7Kz7g_hQvgI&list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'advanced-icon-box' => [
        'name' => 'advanced-icon-box',
        'title' => __('Advanced Icon Box', 'zoloblocks'),
        'categories' => ['others'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/advanced-icon-box',
        'video' => 'https://www.youtube.com/watch?v=i2GqI1LeL34&list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'advanced-image' => [
        'name' => 'advanced-image',
        'title' => __('Advanced Image', 'zoloblocks'),
        'categories' => ['gallery'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/advanced-image',
        'video' => 'https://www.youtube.com/watch?v=Oze-RM3Ke1U&list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'advanced-search' => [
        'name' => 'advanced-search',
        'title' => __('Advanced Search', 'zoloblocks'),
        'categories' => ['others'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/advanced-search',
        'video' => 'https://www.youtube.com/watch?v=2qikAspGriQ&list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'brand-child' => [
        'name' => 'brand-child',
        'title' => __('Brand Child', 'zoloblocks'),
        'categories' => ['list'],
        'status' => true,
        'is_child' => true,
    ],
    'brand-grid' => [
        'name' => 'brand-grid',
        'title' => __('Brand Grid', 'zoloblocks'),
        'categories' => ['list'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/brand-grid',
        'video' => 'https://www.youtube.com/watch?v=zhip0e6rqsE&list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'brand-carousel' => [
        'name' => 'brand-carousel',
        'title' => __('Brand Carousel', 'zoloblocks'),
        'categories' => ['list'],
        'status' => true,
        'is_pro' => true,
        'demo' => 'https://demo.zoloblocks.com/brand-carousel',
        'video' => 'https://www.youtube.com/watch?v=zhip0e6rqsE&list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'business-hour' => [
        'name' => 'business-hour',
        'title' => __('Business Hour', 'zoloblocks'),
        'categories' => ['others'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/business-hour',
        'video' => 'https://www.youtube.com/watch?v=cSShbKq8L9A&list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'charts' => [
        'name' => 'charts',
        'title' => __('Charts', 'zoloblocks'),
        'categories' => ['others'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/charts',
        'video' => 'https://www.youtube.com/watch?v=wr__apvp-xA&list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'countdown' => [
        'name' => 'countdown',
        'title' => __('Countdown', 'zoloblocks'),
        'categories' => ['others'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/countdown',
        'video' => 'https://youtu.be/LQSibSWjLJ4?list=PLFnvpmjcONzI5eoNTbMmjbpYQGdy_zsj8',
    ],
    'counter' => [
        'name' => 'counter',
        'title' => __('Counter', 'zoloblocks'),
        'categories' => ['others'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/counter',
        'video' => 'https://www.youtube.com/watch?v=2ApEaa1cDjo&list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'cta' => [
        'name' => 'cta',
        'title' => __('CTA', 'zoloblocks'),
        'categories' => ['others'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/cta',
        'video' => 'https://www.youtube.com/watch?v=ACXtP0tGT2U&list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'email' => [
        'name' => 'email',
        'title' => __('Email', 'zoloblocks'),
        'categories' => ['others'],
        'status' => true,
        'is_child' => true,
    ],
    'fancy-list' => [
        'name' => 'fancy-list',
        'title' => __('Fancy List', 'zoloblocks'),
        'categories' => ['list'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/fancy-list',
        'video' => 'https://www.youtube.com/watch?v=kp4NtYcYSgY&list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'fancy-list-child' => [
        'name' => 'fancy-list-child',
        'title' => __('Fancy List Child', 'zoloblocks'),
        'categories' => ['list'],
        'status' => true,
        'is_child' => true,
    ],
    'post-featured-image'        => [
        'name'       => 'post-featured-image',
        'class'      => '\Zolo\Blocks\PostFeaturedImage',
        'title'      => __('Post Featured Image', 'zoloblocks'),
        'categories' => ['singlePage'],
        'status'     => true,
        'demo'       => 'https://demo.zoloblocks.com/post-featured-image',
    ],
    'post-comments-form'        => [
        'name'       => 'post-comments-form',
        'class'      => '\Zolo\Blocks\PostCommentsForm',
        'title'      => __('Post Comments Form', 'zoloblocks'),
        'categories' => ['singlePage'],
        'status'     => true,
        'demo'       => 'https://demo.zoloblocks.com/post-comments-form',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'post-navigation'        => [
        'name'       => 'post-navigation',
        'class'      => '\Zolo\Blocks\PostNavigation',
        'title'      => __('Post Navigation', 'zoloblocks'),
        'categories' => ['singlePage'],
        'status'     => true,
        'demo'       => 'https://demo.zoloblocks.com/post-navigation',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'flipbox' => [
        'name' => 'flipbox',
        'title' => __('Flipbox', 'zoloblocks'),
        'categories' => ['others'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/flipbox',
        'video' => 'https://www.youtube.com/watch?v=aymqumvFaX8&list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'form' => [
        'name' => 'form',
        'title' => __('Form', 'zoloblocks'),
        'categories' => ['others'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/form',
        'video' => 'https://www.youtube.com/watch?v=fYpbDbMdlF0&list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'google-map' => [
        'name' => 'google-map',
        'title' => __('Google Map', 'zoloblocks'),
        'categories' => ['others'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/google-map',
        'video' => 'https://www.youtube.com/watch?v=GBkIpWiIY7E&list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'icon' => [
        'name' => 'icon',
        'title' => __('Icon', 'zoloblocks'),
        'categories' => ['others'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/icon',
        'video' => 'https://www.youtube.com/watch?v=ZFwOQr2l5nc&list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'image-compare' => [
        'name' => 'image-compare',
        'title' => __('Image Compare', 'zoloblocks'),
        'categories' => ['gallery'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/image-compare',
        'video' => 'https://www.youtube.com/watch?v=odSQekALYb4&list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'image-gallery' => [
        'name' => 'image-gallery',
        'title' => __('Image Gallery', 'zoloblocks'),
        'categories' => ['gallery'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/image-gallery',
        'video' => 'https://www.youtube.com/watch?v=xa8BLNyM9TQ&list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'list' => [
        'name' => 'list',
        'title' => __('List', 'zoloblocks'),
        'categories' => ['list'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/list',
        'video' => 'https://www.youtube.com/watch?v=iyP9SQ-oIJE&list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'newsletter' => [
        'name' => 'newsletter',
        'title' => __('Newsletter', 'zoloblocks'),
        'categories' => ['others'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/newsletter',
        'video' => 'https://www.youtube.com/watch?v=l57d8W8UTlk&list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'notice' => [
        'name' => 'notice',
        'title' => __('Notice', 'zoloblocks'),
        'categories' => ['others'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/notice',
        'video' => 'https://youtu.be/Tuh1-BeSy2o?list=PLFnvpmjcONzI5eoNTbMmjbpYQGdy_zsj8',
    ],
    'popup-builder' => [
        'name' => 'popup-builder',
        'title' => __('Popup Builder', 'zoloblocks'),
        'categories' => ['others'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/popup-builder',
        'video' => 'https://youtu.be/HPEVm1xGT3I?list=PLFnvpmjcONzLJMQiRFpLAxHsz-RSmZstT',
    ],
    'post-carousel' => [
        'name' => 'post-carousel',
        'class' => '\Zolo\Blocks\PostCarousel',
        'title' => __('Post Carousel', 'zoloblocks'),
        'categories' => ['others'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/post-carousel',
        'video' => 'https://www.youtube.com/watch?v=gOzgkbarICM&list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'post-grid' => [
        'name' => 'post-grid',
        'class' => '\Zolo\Blocks\PostGrid',
        'title' => __('Post Grid', 'zoloblocks'),
        'categories' => ['postCategory', 'list'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/post-grid',
        'video' => 'https://www.youtube.com/watch?v=nqmxNOMQ4tY&list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'post-list' => [
        'name' => 'post-list',
        'class' => '\Zolo\Blocks\PostList',
        'title' => __('Post List', 'zoloblocks'),
        'categories' => ['postCategory', 'list'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/post-list',
        'video' => 'https://www.youtube.com/watch?v=-bP3D2FCGJw&list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'pricing-table' => [
        'name' => 'pricing-table',
        'title' => __('Pricing Table', 'zoloblocks'),
        'categories' => ['others'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/pricing-table',
        'video' => 'https://www.youtube.com/watch?v=LUzMgxWdyMk&list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'profile-card' => [
        'name' => 'profile-card',
        'title' => __('Profile Card', 'zoloblocks'),
        'categories' => ['others'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/profile-card',
        'video' => 'https://youtu.be/OOb3uTcnyZg?list=PLFnvpmjcONzI5eoNTbMmjbpYQGdy_zsj8',
    ],
    'progress-bar' => [
        'name' => 'progress-bar',
        'title' => __('Progress Bar', 'zoloblocks'),
        'categories' => ['others'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/progress-bar',
        'video' => 'https://www.youtube.com/watch?v=vJheNbZr5AA&list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'progress-bar-child' => [
        'name' => 'progress-bar-child',
        'title' => __('Progress Bar Child', 'zoloblocks'),
        'categories' => ['others'],
        'status' => true,
        'is_child' => true,
    ],
    'progress-pie' => [
        'name' => 'progress-pie',
        'title' => __('Progress Pie', 'zoloblocks'),
        'categories' => ['others'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/progress-pie',
        'video' => 'https://www.youtube.com/watch?v=0ccfvIoaGts&list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'qrcode' => [
        'name' => 'qrcode',
        'title' => __('QR Code', 'zoloblocks'),
        'categories' => ['others'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/qr-code',
        'video' => 'https://youtu.be/wcUouKDj5Hk?list=PLFnvpmjcONzI5eoNTbMmjbpYQGdy_zsj8',
    ],
    'review' => [
        'name' => 'review',
        'title' => __('Review', 'zoloblocks'),
        'categories' => ['review'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/review',
        'video' => 'https://www.youtube.com/watch?v=6bBTDdo3PaE&list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'review-carousel' => [
        'name' => 'review-carousel',
        'title' => __('Review Carousel', 'zoloblocks'),
        'categories' => ['review', 'slider'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/review-carousel',
        'video' => 'https://www.youtube.com/watch?v=bbldiWYdCkk&list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'review-child' => [
        'name' => 'review-child',
        'title' => __('Review Child', 'zoloblocks'),
        'categories' => ['review'],
        'status' => true,
        'is_child' => true,
    ],
    'review-grid' => [
        'name' => 'review-grid',
        'title' => __('Review Grid', 'zoloblocks'),
        'categories' => ['review', 'list'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/review-grid',
        'video' => 'https://www.youtube.com/watch?v=Vt04o7SKgUQ&list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'slide' => [
        'name' => 'slide',
        'title' => __('Slide', 'zoloblocks'),
        'categories' => ['slider'],
        'status' => true,
        'is_child' => true,
    ],
    'slider' => [
        'name' => 'slider',
        'title' => __('Slider', 'zoloblocks'),
        'categories' => ['slider'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/slider',
        'video' => 'https://youtu.be/HPEVm1xGT3I?list=PLFnvpmjcONzLJMQiRFpLAxHsz-RSmZstT',
    ],
    'social-links' => [
        'name' => 'social-links',
        'title' => __('Social Links', 'zoloblocks'),
        'categories' => ['social'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/social-links',
        'video' => 'https://www.youtube.com/watch?v=37RHK27M5QE&list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'social-share' => [
        'name' => 'social-share',
        'title' => __('Social Share', 'zoloblocks'),
        'categories' => ['social'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/social-share',
        'video' => 'https://www.youtube.com/watch?v=28QZIV6UXxk&list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'spline-viewer' => [
        'name' => 'spline-viewer',
        'title' => __('Spline Viewer', 'zoloblocks'),
        'categories' => ['others'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/spine-viewer',
        'video' => 'https://youtu.be/HPEVm1xGT3I?list=PLFnvpmjcONzLJMQiRFpLAxHsz-RSmZstT',
    ],
    'star-rating' => [
        'name' => 'star-rating',
        'title' => __('Star Rating', 'zoloblocks'),
        'categories' => ['review'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/star-rating',
        'video' => 'https://www.youtube.com/watch?v=fZZxJUSRLbI&list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'tab' => [
        'name' => 'tab',
        'title' => __('Tab', 'zoloblocks'),
        'categories' => ['others'],
        'status' => true,
        'is_child' => true,
    ],
    'tabs' => [
        'name' => 'tabs',
        'title' => __('Tabs', 'zoloblocks'),
        'categories' => ['others'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/tabs',
        'video' => 'https://youtu.be/o8S5EiBxM2M?list=PLFnvpmjcONzI5eoNTbMmjbpYQGdy_zsj8',
    ],
    'team-grid' => [
        'name' => 'team-grid',
        'title' => __('Team Grid', 'zoloblocks'),
        'categories' => ['list'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/team-grid',
        'video' => 'https://www.youtube.com/watch?v=JK-lNriWs4Q&list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'team-child' => [
        'name' => 'team-child',
        'title' => __('Team Grid', 'zoloblocks'),
        'categories' => ['list'],
        'status' => true,
        'is_child' => true,
    ],
    'text-field' => [
        'name' => 'text-field',
        'title' => __('Text Field', 'zoloblocks'),
        'categories' => ['others'],
        'status' => true,
        'is_child' => true,
    ],
    'text-path' => [
        'name' => 'text-path',
        'title' => __('Text Path', 'zoloblocks'),
        'categories' => ['others'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/text-path',
        'video' => 'https://youtu.be/k-ThzRoErVo?list=PLFnvpmjcONzI5eoNTbMmjbpYQGdy_zsj8',
    ],
    'textarea' => [
        'name' => 'textarea',
        'title' => __('Textarea', 'zoloblocks'),
        'categories' => ['others'],
        'status' => true,
        'is_child' => true,
    ],
    'post-category' => [
        'name' => 'post-category',
        'class' => '\Zolo\Blocks\PostCategory',
        'title' => __('Post Category', 'zoloblocks'),
        'categories' => ['postCategory', 'list'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/post-category',
        'video' => 'https://youtu.be/vx3sRLIMVWk?list=PLFnvpmjcONzI5eoNTbMmjbpYQGdy_zsj8',
    ],
    'post-timeline' => [
        'name' => 'post-timeline',
        'class' => '\Zolo\Blocks\PostTimeline',
        'title' => __('Post Timeline', 'zoloblocks'),
        'categories' => ['list'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/post-timeline',
        'video' => 'https://youtu.be/PNVBQz5GwvM?list=PLFnvpmjcONzI5eoNTbMmjbpYQGdy_zsj8',
    ],
    'tag-cloud' => [
        'name' => 'tag-cloud',
        'class' => '\Zolo\Blocks\TagCloud',
        'title' => __('Tag Cloud', 'zoloblocks'),
        'categories' => ['others'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/tag-cloud',
        'video' => 'https://youtu.be/w1RKAO30GaI?list=PLFnvpmjcONzI5eoNTbMmjbpYQGdy_zsj8',
    ],
    'post-list' => [
        'name' => 'post-list',
        'class' => '\Zolo\Blocks\PostList',
        'title' => __('Post List', 'zoloblocks'),
        'categories' => ['postCategory', 'list'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/post-list',
        'video' => 'https://www.youtube.com/watch?v=-bP3D2FCGJw&list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'lightbox' => [
        'name' => 'lightbox',
        'title' => __('Lightbox', 'zoloblocks'),
        'categories' => ['gallery'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/lightbox',
        'video' => 'https://youtu.be/FFQ9I3fNWKw?list=PLFnvpmjcONzI5eoNTbMmjbpYQGdy_zsj8',
    ],
    'author' => [
        'name' => 'author',
        'class' => '\Zolo\Blocks\Author',
        'title' => __('Author', 'zoloblocks'),
        'categories' => ['others'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/author',
        'video' => 'https://youtu.be/WxLi-c7lhpI?list=PLFnvpmjcONzI5eoNTbMmjbpYQGdy_zsj8',
    ],
    'social-count' => [
        'name' => 'social-count',
        'title' => __('Social Count', 'zoloblocks'),
        'categories' => ['others'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/social-count',
        'video' => 'https://youtu.be/nUCWsk776qM?list=PLFnvpmjcONzI5eoNTbMmjbpYQGdy_zsj8',
    ],
    'social-count-child' => [
        'name' => 'social-count-child',
        'title' => __('Social Count Child', 'zoloblocks'),
        'categories' => ['others'],
        'status' => true,
        'is_child' => true,
    ],
    'spline-viewer' => [
        'name' => 'spline-viewer',
        'title' => __('Spline Viewer', 'zoloblocks'),
        'categories' => ['others'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/spline-viewer',
        'video' => 'https://youtu.be/HPEVm1xGT3I?list=PLFnvpmjcONzLJMQiRFpLAxHsz-RSmZstT',
    ],
    'post-comments' => [
        'name' => 'post-comments',
        'class' => '\Zolo\Blocks\PostComments',
        'title' => __('Post Comments', 'zoloblocks'),
        'categories' => ['others'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/post-comments',
        'video' => 'https://youtu.be/HPEVm1xGT3I?list=PLFnvpmjcONzLJMQiRFpLAxHsz-RSmZstT',
    ],
    'breadcrumbs' => [
        'name' => 'breadcrumbs',
        'class' => '\Zolo\Blocks\BreadcrumbsBlock',
        'title' => __('Breadcrumbs', 'zoloblocks'),
        'categories' => ['others'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/breadcrumbs',
        'video' => 'https://youtu.be/ixtp0Ko9abs?list=PLFnvpmjcONzI5eoNTbMmjbpYQGdy_zsj8',
    ],
    'post-title'        => [
        'name'       => 'post-title',
        'class'      => '\Zolo\Blocks\PostTitle',
        'title'      => __('Post Title', 'zoloblocks'),
        'categories' => ['singlePage'],
        'status'     => true,
        'demo'       => 'https://demo.zoloblocks.com/post-title',
        'video'      => 'https://youtu.be/HPEVm1xGT3I?list=PLFnvpmjcONzLJMQiRFpLAxHsz-RSmZstT',
    ],
    'unfold' => [
        'name' => 'unfold',
        'title' => __('Unfold', 'zoloblocks-pro'),
        'categories' => ['others'],
        'status' => true,
        'is_pro' => true,
        'demo' => 'https://demo.zoloblocks.com/unfold',
        'video' => 'https://youtu.be/PlJpChsfFvM?list=PLFnvpmjcONzI5eoNTbMmjbpYQGdy_zsj8',
    ],
    'data-table' => [
        'name' => 'data-table',
        'title' => __('Data Table', 'zoloblocks-pro'),
        'categories' => ['others'],
        'status' => true,
        'is_pro' => true,
        'demo' => 'https://demo.zoloblocks.com/data-table',
        'video' => 'https://youtu.be/3ea3t7Pvoo4',
    ],
    'image-hotspot' => [
        'name' => 'image-hotspot',
        'title' => __('Image Hotspot', 'zoloblocks-pro'),
        'categories' => ['gallery'],
        'status' => true,
        'is_pro' => true,
        'demo' => 'https://demo.zoloblocks.com/image-hotspot',
        'video' => 'https://youtu.be/Vp6K0_l-t20',
    ],
    'navigation' => [
        'name' => 'navigation',
        'title' => __('Navigation', 'zoloblocks'),
        'categories' => ['others'],
        'status' => true,
        'demo' => 'https: //demo.zoloblocks.com/navigation',
        'video' => 'https: //youtu.be/8kBMIL-4PZI?list = PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'navigation-item' => [
        'name' => 'navigation-item',
        'title' => __('Navigation Item', 'zoloblocks'),
        'categories' => ['others'],
        'status' => true,
        'demo' => 'https: //demo.zoloblocks.com/navigation-item',
        'video' => 'https: //youtu.be/8kBMIL-4PZI?list = PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
        'is_child' => true,
    ],
    'navigation-submenu' => [
        'name' => 'navigation-submenu',
        'title' => __('Navigation Submenu', 'zoloblocks'),
        'categories' => ['others'],
        'status' => true,
        'demo' => 'https: //demo.zoloblocks.com/navigation-submenu',
        'video' => 'https: //youtu.be/8kBMIL-4PZI?list = PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
        'is_child' => true,
    ],
    'megamenu' => [
        'name' => 'megamenu',
        'title' => __('Mega Menu', 'zoloblocks'),
        'categories' => ['others'],
        'status' => true,
        'demo' => 'https: //demo.zoloblocks.com/megamenu',
        'video' => 'https: //youtu.be/8kBMIL-4PZI?list = PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
        'is_child' => true,
    ],
    'post-meta' => [
        'name' => 'post-meta',
        'class' => '\Zolo\Blocks\PostMeta',
        'title' => __('Post Meta', 'zoloblocks'),
        'categories' => ['singlePage'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/post-meta',
        'video' => 'https://youtu.be/HPEVm1xGT3I?list=PLFnvpmjcONzLJMQiRFpLAxHsz-RSmZstT',
    ],
    'marquee' => [
        'name' => 'marquee',
        'title' => __('Marquee', 'zoloblocks-pro'),
        'categories' => ['gallery'],
        'status' => true,
        'is_pro' => true,
        'demo' => 'https://demo.zoloblocks.com/marquee',
        'video' => 'https://youtu.be/u_ObTjHo5HU',
    ],
    'table-of-content' => [
        'name' => 'table-of-content',
        'title' => __('Table of Content', 'zolo-blocks'),
        'categories' => ['others'],
        'status' => true,
        'demo' => 'https: //demo.zoloblocks.com/table-of-content',
        'video' => 'https: //youtu.be/8kBMIL-4PZI?list = PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'marquee-child' => [
        'name' => 'marquee-child',
        'title' => __('Marquee Child', 'zoloblocks-pro'),
        'categories' => ['post'],
        'status' => true,
        'is_pro' => true,
        'is_child' => true,
    ],
    'post-tab' => [
        'name' => 'post-tab',
        'title' => __('Post Tab', 'zoloblocks-pro'),
        'categories' => ['postCategory'],
        'class'      => '\ZoloPro\Blocks\PostTab',
        'status'     => true,
        'is_pro'     => true,
        'demo'       => 'https://demo.zoloblocks.com/post-tab',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'post-query'           => [
        'name'             => 'post-query',
        'title'            => __('Post Query', 'zoloblocks'),
        'categories'       => ['others'],
        'status'           => true,
        'is_pro'           => true,
        'class'            => '\ZoloPro\Blocks\PostQuery',
        'demo'             => 'https://demo.zoloblocks.com/post-query',
        'video'            => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'loop'               => [
        'name'       => 'loop',
        'title'      => __('Loop', 'zoloblocks'),
        'categories' => ['others'],
        'status'     => true,
        'is_pro'     => true,
        'class'      => '\ZoloPro\Blocks\Loop',
        'demo'       => 'https://demo.zoloblocks.com/loop',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'query-pagination' => [
        'name'       => 'query-pagination',
        'title'      => __('Query Pagination', 'zoloblocks'),
        'categories' => ['others'],
        'status'     => true,
        'is_pro'     => true,
        'class'      => '\ZoloPro\Blocks\QueryPagination',
        'demo'       => 'https://demo.zoloblocks.com/query-pagination',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'post-content'        => [
        'name'       => 'post-content',
        'class'      => '\Zolo\Blocks\PostContent',
        'title'      => __('Post Content', 'zoloblocks'),
        'categories' => ['singlePage'],
        'status'     => true,
        'demo'       => 'https://demo.zoloblocks.com/post-content',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'advanced-paragraph' => [
        'name' => 'advanced-paragraph',
        'title' => __('Advanced Paragraph', 'zoloblocks-pro'),
        'categories' => ['others'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/advanced-paragraph',
        'video' => 'https://youtu.be/HPEVm1xGT3I?list=PLFnvpmjcONzLJMQiRFpLAxHsz-RSmZstT',
    ],
    'datetime-field' => [
        'name' => 'datetime-field',
        'title' => __('Date Time Field', 'zoloblocks-pro'),
        'categories' => ['others'],
        'status' => true,
        'is_child' => true,
    ],
    'checkbox-field' => [
        'name' => 'checkbox-field',
        'title' => __('Checkbox Field', 'zoloblocks'),
        'categories' => ['others'],
        'status' => true,
        'is_child' => true,
    ],
    'phonenumber-field' => [
        'name' => 'phonenumber-field',
        'title' => __('Phone Number', 'zoloblocks-pro'),
        'categories' => ['others'],
        'status' => true,
        'is_pro' => true,
    ],
    'country-field' => [
        'name' => 'country-field',
        'title' => __('Country Field', 'zoloblocks-pro'),
        'categories' => ['others'],
        'status' => true,
        'is_pro' => true,
    ],
    'select-field' => [
        'name' => 'select-field',
        'title' => __('Select Field', 'zoloblocks'),
        'categories' => ['others'],
        'status' => true,
        'is_child' => true,
    ],
    'post-video-slider' => [
        'name' => 'post-video-slider',
        'title' => __('Post Video Slider', 'zoloblocks-pro'),
        'categories' => ['postCategory'],
        'class' => '\ZoloPro\Blocks\PostVideoSlider',
        'status' => true,
        'is_pro' => true,
        'demo' => 'https://demo.zoloblocks.com/marquee',
        'video' => 'https://youtu.be/HPEVm1xGT3I?list=PLFnvpmjcONzLJMQiRFpLAxHsz-RSmZstT',
    ],
    'lottie-image' => [
        'name' => 'lottie-image',
        'title' => __('Lottie Image', 'zoloblocks-pro'),
        'categories' => ['others'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/lottie-image',
        'video' => 'https://youtu.be/HPEVm1xGT3I?list=PLFnvpmjcONzLJMQiRFpLAxHsz-RSmZstT',
    ],
    'number-field' => [
        'name' => 'number-field',
        'title' => __('Number Field', 'zoloblocks'),
        'categories' => ['others'],
        'status' => true,
        'is_child' => true,
    ],
    'radio-field' => [
        'name' => 'radio-field',
        'title' => __('Radio Field', 'zoloblocks'),
        'categories' => ['others'],
        'status' => true,
        'is_child' => true,
    ]
]);
