<?php
require_once ZOLO_DIR_PATH . 'includes/Blocks/PostGrid.php';
require_once ZOLO_DIR_PATH . 'includes/Blocks/PostList.php';

return apply_filters('zolo_blocks_list_data', [
    'container' => [
        'name' => 'container',
        'title' => __('Container', 'zoloblocks'),
        'categories' => ['others'],
        'status' => true,
        'demo' => 'https://zoloblocks.com',
        'video' => 'https://youtu.be/HPEVm1xGT3I?list=PLFnvpmjcONzLJMQiRFpLAxHsz-RSmZstT',
    ],
    'advanced-paragraph' => [
        'name' => 'advanced-paragraph',
        'title' => __('Advanced Paragraph', 'zoloblocks-pro'),
        'categories' => ['others'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/advanced-paragraph',
        'video' => 'https://youtu.be/HPEVm1xGT3I?list=PLFnvpmjcONzLJMQiRFpLAxHsz-RSmZstT',
    ],
    'accordion' => [
        'name' => 'accordion',
        'title' => __('Accordion', 'zoloblocks'),
        'categories' => ['others'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/accordion',
        'video' => 'https://www.youtube.com/watch?v=s8Vkj69fr-Q',
    ],
    'accordion-child' => [
        'name' => 'accordion-child',
        'title' => __('Accordion Child', 'zoloblocks'),
        'categories' => ['others'],
        'status' => true,
        'is_child' => true,
    ],
    'advanced-button' => [
        'name' => 'advanced-button',
        'title' => __('Advanced Button', 'zoloblocks'),
        'categories' => ['others'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/advanced-button',
        'video' => 'https://www.youtube.com/watch?v=H10lSIUc-zo',
    ],
    'advanced-heading' => [
        'name' => 'advanced-heading',
        'title' => __('Advanced Heading', 'zoloblocks'),
        'categories' => ['others'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/advanced-heading',
        'video' => 'https://www.youtube.com/watch?v=RzuQGv2xDeI',
    ],
    'advanced-icon-box' => [
        'name' => 'advanced-icon-box',
        'title' => __('Advanced Icon Box', 'zoloblocks'),
        'categories' => ['others'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/advanced-icon-box',
        'video' => 'https://www.youtube.com/watch?v=I3YUMalIefA',
    ],
    'advanced-image' => [
        'name' => 'advanced-image',
        'title' => __('Advanced Image', 'zoloblocks'),
        'categories' => ['gallery'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/advanced-image',
        'video' => 'https://www.youtube.com/watch?v=OypRfBlGZ28',
    ],
    'advanced-search' => [
        'name' => 'advanced-search',
        'title' => __('Advanced Search', 'zoloblocks'),
        'categories' => ['others'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/advanced-search',
        'video' => 'https://www.youtube.com/watch?v=7x_LFo9sVsE',
    ],
    'brand-child' => [
        'name' => 'brand-child',
        'title' => __('Brand Child', 'zoloblocks'),
        'categories' => ['list'],
        'status' => true,
        'is_child' => true,
    ],
    'brand-grid' => [
        'name' => 'brand-grid',
        'title' => __('Brand Grid', 'zoloblocks'),
        'categories' => ['list'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/brand-grid',
        'video' => 'https://www.youtube.com/watch?v=A9gg4QA1nLo',
    ],
    'brand-carousel' => [
        'name' => 'brand-carousel',
        'title' => __('Brand Carousel', 'zoloblocks'),
        'categories' => ['list'],
        'status' => true,
        'is_pro' => true,
        'demo' => 'https://demo.zoloblocks.com/brand-carousel',
        'video' => 'https://www.youtube.com/watch?v=ht3dVsz6yCY',
    ],
    'brand-carousel-child' => [
        'name' => 'brand-carousel-child',
        'title' => __('Brand Carousel Child', 'zoloblocks-pro'),
        'categories' => ['post'],
        'status' => true,
        'is_pro' => true,
        'is_child' => true,
    ],
    'business-hour' => [
        'name' => 'business-hour',
        'title' => __('Business Hour', 'zoloblocks'),
        'categories' => ['others'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/business-hour',
        'video' => 'https://www.youtube.com/watch?v=4eCjKZTOcMU',
    ],
    'charts' => [
        'name' => 'charts',
        'title' => __('Charts', 'zoloblocks'),
        'categories' => ['others'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/charts',
        'video' => 'https://www.youtube.com/watch?v=Fi3j9LReukk',
    ],
    'countdown' => [
        'name' => 'countdown',
        'title' => __('Countdown', 'zoloblocks'),
        'categories' => ['others'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/countdown',
        'video' => 'https://www.youtube.com/watch?v=LQSibSWjLJ4',
    ],
    'counter' => [
        'name' => 'counter',
        'title' => __('Counter', 'zoloblocks'),
        'categories' => ['others'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/counter',
        'video' => 'https://www.youtube.com/watch?v=he5VGbE0MmU',
    ],
    'cta' => [
        'name' => 'cta',
        'title' => __('CTA', 'zoloblocks'),
        'categories' => ['others'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/cta',
        'video' => 'https://www.youtube.com/watch?v=R0mIoHUckgk',
    ],
    'fancy-list' => [
        'name' => 'fancy-list',
        'title' => __('Fancy List', 'zoloblocks'),
        'categories' => ['list'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/fancy-list',
        'video' => 'https://www.youtube.com/watch?v=EbKbp0iELeo',
    ],
    'fancy-list-child' => [
        'name' => 'fancy-list-child',
        'title' => __('Fancy List Child', 'zoloblocks'),
        'categories' => ['list'],
        'status' => true,
        'is_child' => true,
    ],
    'post-featured-image'        => [
        'name'       => 'post-featured-image',
        'class'      => '\Zolo\Blocks\PostFeaturedImage',
        'title'      => __('Post Featured Image', 'zoloblocks'),
        'categories' => ['singlePage'],
        'status'     => true,
        'demo'       => 'https://demo.zoloblocks.com/post-featured-image',
    ],
    'post-comments-form'        => [
        'name'       => 'post-comments-form',
        'class'      => '\Zolo\Blocks\PostCommentsForm',
        'title'      => __('Post Comments Form', 'zoloblocks'),
        'categories' => ['singlePage'],
        'status'     => true,
        'demo'       => 'https://demo.zoloblocks.com/post-comments-form',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'post-navigation'        => [
        'name'       => 'post-navigation',
        'class'      => '\Zolo\Blocks\PostNavigation',
        'title'      => __('Post Navigation', 'zoloblocks'),
        'categories' => ['singlePage'],
        'status'     => true,
        'demo'       => 'https://demo.zoloblocks.com/post-navigation',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'flipbox' => [
        'name' => 'flipbox',
        'title' => __('Flipbox', 'zoloblocks'),
        'categories' => ['others'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/flipbox',
        'video' => 'https://www.youtube.com/watch?v=8lSVH3qP-ck',
    ],
    'google-map' => [
        'name' => 'google-map',
        'title' => __('Google Map', 'zoloblocks'),
        'categories' => ['others'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/google-map',
        'video' => 'https://www.youtube.com/watch?v=N3UoMpV9ZUI',
    ],
    'icon' => [
        'name' => 'icon',
        'title' => __('Icon', 'zoloblocks'),
        'categories' => ['others'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/icon',
        'video' => 'https://www.youtube.com/watch?v=8WAuHkJDA_Q',
    ],
    'image-compare' => [
        'name' => 'image-compare',
        'title' => __('Image Compare', 'zoloblocks'),
        'categories' => ['gallery'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/image-compare',
        'video' => 'https://www.youtube.com/watch?v=RcqjBFolrNc',
    ],
    'image-gallery' => [
        'name' => 'image-gallery',
        'title' => __('Image Gallery', 'zoloblocks'),
        'categories' => ['gallery'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/image-gallery',
        'video' => 'https://www.youtube.com/watch?v=phWMyjhT92c',
    ],
    'list' => [
        'name' => 'list',
        'title' => __('List', 'zoloblocks'),
        'categories' => ['list'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/list',
        'video' => 'https://www.youtube.com/watch?v=sHkc1OpULBM',
    ],
    'newsletter' => [
        'name' => 'newsletter',
        'title' => __('Newsletter', 'zoloblocks'),
        'categories' => ['others'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/newsletter',
        'video' => 'https://www.youtube.com/watch?v=X0ujGvofUsI',
    ],
    'notice' => [
        'name' => 'notice',
        'title' => __('Notice', 'zoloblocks'),
        'categories' => ['others'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/notice',
        'video' => 'https://www.youtube.com/watch?v=Tuh1-BeSy2o',
    ],
    'popup-builder' => [
        'name' => 'popup-builder',
        'title' => __('Popup Builder', 'zoloblocks'),
        'categories' => ['others'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/popup-builder',
        'video' => 'https://www.youtube.com/watch?v=THJ9yuvPBBk&t',
    ],
    'post-carousel' => [
        'name' => 'post-carousel',
        'class' => '\Zolo\Blocks\PostCarousel',
        'title' => __('Post Carousel', 'zoloblocks'),
        'categories' => ['others'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/post-carousel',
        'video' => 'https://www.youtube.com/watch?v=0HJMfBeB7aY',
    ],
    'post-grid' => [
        'name' => 'post-grid',
        'class' => '\Zolo\Blocks\PostGrid',
        'title' => __('Post Grid', 'zoloblocks'),
        'categories' => ['postCategory', 'list'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/post-grid',
        'video' => 'https://www.youtube.com/watch?v=4rv2XYR8AgE',
    ],
    'post-list' => [
        'name' => 'post-list',
        'class' => '\Zolo\Blocks\PostList',
        'title' => __('Post List', 'zoloblocks'),
        'categories' => ['postCategory', 'list'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/post-list',
        'video' => 'https://www.youtube.com/watch?v=ciobz-UMyak',
    ],
    'pricing-table' => [
        'name' => 'pricing-table',
        'title' => __('Pricing Table', 'zoloblocks'),
        'categories' => ['others'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/pricing-table',
        'video' => 'https://www.youtube.com/watch?v=dU5G7ctyFSQ',
    ],
    'profile-card' => [
        'name' => 'profile-card',
        'title' => __('Profile Card', 'zoloblocks'),
        'categories' => ['others'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/profile-card',
        'video' => 'https://www.youtube.com/watch?v=OOb3uTcnyZg',
    ],
    'progress-bar' => [
        'name' => 'progress-bar',
        'title' => __('Progress Bar', 'zoloblocks'),
        'categories' => ['others'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/progress-bar',
        'video' => 'https://www.youtube.com/watch?v=2e1hlFVh2mY',
    ],
    'progress-bar-child' => [
        'name' => 'progress-bar-child',
        'title' => __('Progress Bar Child', 'zoloblocks'),
        'categories' => ['others'],
        'status' => true,
        'is_child' => true,
    ],
    'progress-pie' => [
        'name' => 'progress-pie',
        'title' => __('Progress Pie', 'zoloblocks'),
        'categories' => ['others'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/progress-pie',
        'video' => 'https://www.youtube.com/watch?v=rCGiKOBSKds',
    ],
    'qrcode' => [
        'name' => 'qrcode',
        'title' => __('QR Code', 'zoloblocks'),
        'categories' => ['others'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/qr-code',
        'video' => 'https://www.youtube.com/watch?v=wcUouKDj5Hk',
    ],
    'review' => [
        'name' => 'review',
        'title' => __('Review', 'zoloblocks'),
        'categories' => ['review'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/review',
        'video' => 'https://www.youtube.com/watch?v=gao050QI3L4',
    ],
    'review-carousel' => [
        'name' => 'review-carousel',
        'title' => __('Review Carousel', 'zoloblocks'),
        'categories' => ['review', 'slider'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/review-carousel',
        'video' => 'https://www.youtube.com/watch?v=r4UHviOUVBc',
    ],
    'review-child' => [
        'name' => 'review-child',
        'title' => __('Review Child', 'zoloblocks'),
        'categories' => ['review'],
        'status' => true,
        'is_child' => true,
    ],
    'review-grid' => [
        'name' => 'review-grid',
        'title' => __('Review Grid', 'zoloblocks'),
        'categories' => ['review', 'list'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/review-grid',
        'video' => 'https://www.youtube.com/watch?v=iGkYmeLlc8g',
    ],
    'slide' => [
        'name' => 'slide',
        'title' => __('Slide', 'zoloblocks'),
        'categories' => ['slider'],
        'status' => true,
        'is_child' => true,
    ],
    'slider' => [
        'name' => 'slider',
        'title' => __('Slider', 'zoloblocks'),
        'categories' => ['slider'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/slider',
        'video' => 'https://youtu.be/HPEVm1xGT3I?list=PLFnvpmjcONzLJMQiRFpLAxHsz-RSmZstT',
    ],
    'social-links' => [
        'name' => 'social-links',
        'title' => __('Social Links', 'zoloblocks'),
        'categories' => ['others'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/social-links',
        'video' => 'https://www.youtube.com/watch?v=mth43iWaB-k',
    ],
    'social-share' => [
        'name' => 'social-share',
        'title' => __('Social Share', 'zoloblocks'),
        'categories' => ['others'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/social-share',
        'video' => 'https://www.youtube.com/watch?v=rMTj9djbWbk',
    ],
    'spline-viewer' => [
        'name' => 'spline-viewer',
        'title' => __('Spline Viewer', 'zoloblocks'),
        'categories' => ['others'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/spine-viewer',
        'video' => 'https://www.youtube.com/watch?v=VzvBorWtHgo&t',
    ],
    'star-rating' => [
        'name' => 'star-rating',
        'title' => __('Star Rating', 'zoloblocks'),
        'categories' => ['review'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/star-rating',
        'video' => 'https://www.youtube.com/watch?v=5EwTX51jYlg',
    ],
    'tab' => [
        'name' => 'tab',
        'title' => __('Tab', 'zoloblocks'),
        'categories' => ['others'],
        'status' => true,
        'is_child' => true,
    ],
    'tabs' => [
        'name' => 'tabs',
        'title' => __('Tabs', 'zoloblocks'),
        'categories' => ['others'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/tabs',
        'video' => 'https://www.youtube.com/watch?v=o8S5EiBxM2M',
    ],
    'team-grid' => [
        'name' => 'team-grid',
        'title' => __('Team Grid', 'zoloblocks'),
        'categories' => ['list'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/team-grid',
        'video' => 'https://www.youtube.com/watch?v=RWsiDcOcEqE',
    ],
    'team-child' => [
        'name' => 'team-child',
        'title' => __('Team Grid', 'zoloblocks'),
        'categories' => ['list'],
        'status' => true,
        'is_child' => true,
    ],
    'text-path' => [
        'name' => 'text-path',
        'title' => __('Text Path', 'zoloblocks'),
        'categories' => ['others'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/text-path',
        'video' => 'https://www.youtube.com/watch?v=k-ThzRoErVo',
    ],

    'post-category' => [
        'name' => 'post-category',
        'class' => '\Zolo\Blocks\PostCategory',
        'title' => __('Post Category', 'zoloblocks'),
        'categories' => ['postCategory', 'list'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/post-category',
        'video' => 'https://www.youtube.com/watch?v=vx3sRLIMVWk&t',
    ],
    'post-timeline' => [
        'name' => 'post-timeline',
        'class' => '\Zolo\Blocks\PostTimeline',
        'title' => __('Post Timeline', 'zoloblocks'),
        'categories' => ['list'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/post-timeline',
        'video' => 'https://www.youtube.com/watch?v=PNVBQz5GwvM',
    ],
    'tag-cloud' => [
        'name' => 'tag-cloud',
        'class' => '\Zolo\Blocks\TagCloud',
        'title' => __('Tag Cloud', 'zoloblocks'),
        'categories' => ['others'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/tag-cloud',
        'video' => 'https://www.youtube.com/watch?v=w1RKAO30GaI',
    ],
    'post-list' => [
        'name' => 'post-list',
        'class' => '\Zolo\Blocks\PostList',
        'title' => __('Post List', 'zoloblocks'),
        'categories' => ['postCategory', 'list'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/post-list',
        'video' => 'https://www.youtube.com/watch?v=ciobz-UMyak',
    ],
    'lightbox' => [
        'name' => 'lightbox',
        'title' => __('Lightbox', 'zoloblocks'),
        'categories' => ['gallery'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/lightbox',
        'video' => 'https://www.youtube.com/watch?v=FFQ9I3fNWKw&t',
    ],
    'author' => [
        'name' => 'author',
        'class' => '\Zolo\Blocks\Author',
        'title' => __('Author', 'zoloblocks'),
        'categories' => ['others'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/author',
        'video' => 'https://www.youtube.com/watch?v=WxLi-c7lhpI',
    ],
    'social-count' => [
        'name' => 'social-count',
        'title' => __('Social Count', 'zoloblocks'),
        'categories' => ['others'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/social-count',
        'video' => 'https://www.youtube.com/watch?v=nUCWsk776qM',
    ],
    'social-count-child' => [
        'name' => 'social-count-child',
        'title' => __('Social Count Child', 'zoloblocks'),
        'categories' => ['others'],
        'status' => true,
        'is_child' => true,
    ],
    'post-comments' => [
        'name' => 'post-comments',
        'class' => '\Zolo\Blocks\PostComments',
        'title' => __('Post Comments', 'zoloblocks'),
        'categories' => ['others'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/post-comments',
        'video' => 'https://www.youtube.com/watch?v=MamMiQE2gzg&t',
    ],
    'breadcrumbs' => [
        'name' => 'breadcrumbs',
        'class' => '\Zolo\Blocks\BreadcrumbsBlock',
        'title' => __('Breadcrumbs', 'zoloblocks'),
        'categories' => ['others'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/breadcrumbs',
        'video' => 'https://www.youtube.com/watch?v=ixtp0Ko9abs',
    ],
    'post-title'        => [
        'name'       => 'post-title',
        'class'      => '\Zolo\Blocks\PostTitle',
        'title'      => __('Post Title', 'zoloblocks'),
        'categories' => ['singlePage'],
        'status'     => true,
        'demo'       => 'https://demo.zoloblocks.com/post-title',
        'video'      => 'https://youtu.be/HPEVm1xGT3I?list=PLFnvpmjcONzLJMQiRFpLAxHsz-RSmZstT',
    ],
    'unfold' => [
        'name' => 'unfold',
        'title' => __('Unfold', 'zoloblocks-pro'),
        'categories' => ['others'],
        'status' => true,
        'is_pro' => true,
        'demo' => 'https://demo.zoloblocks.com/unfold',
        'video' => 'https://www.youtube.com/watch?v=PlJpChsfFvM&t',
    ],
    'data-table' => [
        'name' => 'data-table',
        'title' => __('Data Table', 'zoloblocks-pro'),
        'categories' => ['others'],
        'status' => true,
        'is_pro' => true,
        'demo' => 'https://demo.zoloblocks.com/data-table',
        'video' => 'https://www.youtube.com/watch?v=0oCc6LnACwc',
    ],
    'image-hotspot' => [
        'name' => 'image-hotspot',
        'title' => __('Image Hotspot', 'zoloblocks-pro'),
        'categories' => ['gallery'],
        'status' => true,
        'is_pro' => true,
        'demo' => 'https://demo.zoloblocks.com/image-hotspot',
        'video' => 'https://www.youtube.com/watch?v=qR9Ua6wuxrA',
    ],
    'navigation' => [
        'name' => 'navigation',
        'title' => __('Navigation', 'zoloblocks'),
        'categories' => ['others'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/navigation',
        'video' => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'navigation-item' => [
        'name' => 'navigation-item',
        'title' => __('Navigation Item', 'zoloblocks'),
        'categories' => ['others'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/navigation-item',
        'video' => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
        'is_child' => true,
    ],
    'navigation-submenu' => [
        'name' => 'navigation-submenu',
        'title' => __('Navigation Submenu', 'zoloblocks'),
        'categories' => ['others'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/navigation-submenu',
        'video' => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
        'is_child' => true,
    ],
    'megamenu' => [
        'name' => 'megamenu',
        'title' => __('Mega Menu', 'zoloblocks'),
        'categories' => ['others'],
        'status' => true,
        'is_child' => true,
        'demo' => 'https://demo.zoloblocks.com/megamenu',
        'video' => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'post-meta' => [
        'name' => 'post-meta',
        'class' => '\Zolo\Blocks\PostMeta',
        'title' => __('Post Meta', 'zoloblocks'),
        'categories' => ['singlePage'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/post-meta',
        'video' => 'https://youtu.be/HPEVm1xGT3I?list=PLFnvpmjcONzLJMQiRFpLAxHsz-RSmZstT',
    ],
    'marquee' => [
        'name' => 'marquee',
        'title' => __('Marquee', 'zoloblocks-pro'),
        'categories' => ['gallery'],
        'status' => true,
        'is_pro' => true,
        'demo' => 'https://demo.zoloblocks.com/marquee',
        'video' => 'https://youtu.be/u_ObTjHo5HU',
    ],
    'marquee-child' => [
        'name' => 'marquee-child',
        'title' => __('Marquee Child', 'zoloblocks-pro'),
        'categories' => ['post'],
        'status' => true,
        'is_pro' => true,
        'is_child' => true,
    ],
    'table-of-content' => [
        'name' => 'table-of-content',
        'title' => __('Table of Content', 'zolo-blocks'),
        'categories' => ['others'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/table-of-content',
        'video' => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'post-tab' => [
        'name' => 'post-tab',
        'title' => __('Post Tab', 'zoloblocks-pro'),
        'categories' => ['postCategory'],
        'class'      => '\ZoloPro\Blocks\PostTab',
        'status'     => true,
        'is_pro'     => true,
        'demo'       => 'https://demo.zoloblocks.com/post-tab',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'loop-builder'           => [
        'name'             => 'loop-builder',
        'title'            => __('Loop Builder', 'zoloblocks'),
        'categories'       => ['others'],
        'status'           => true,
        'is_pro'           => true,
        'class'            => '\ZoloPro\Blocks\PostQuery',
        'demo'             => 'https://demo.zoloblocks.com/loop-builder',
        'video'            => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'loop'               => [
        'name'       => 'loop',
        'title'      => __('Loop', 'zoloblocks'),
        'categories' => ['others'],
        'status'     => true,
        'is_pro'     => true,
        'is_child'   => true,
        'class'      => '\ZoloPro\Blocks\Loop',
        'demo'       => 'https://demo.zoloblocks.com/loop',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'loop-pagination' => [
        'name'       => 'loop-pagination',
        'title'      => __('Loop Pagination', 'zoloblocks'),
        'categories' => ['others'],
        'status'     => true,
        'is_pro'     => true,
        'is_child'   => true,
        'class'      => '\ZoloPro\Blocks\QueryPagination',
        'demo'       => 'https://demo.zoloblocks.com/loop-pagination',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'post-content'        => [
        'name'       => 'post-content',
        'class'      => '\Zolo\Blocks\PostContent',
        'title'      => __('Post Content', 'zoloblocks'),
        'categories' => ['singlePage'],
        'status'     => true,
        'demo'       => 'https://demo.zoloblocks.com/post-content',
        'video'      => 'https://youtu.be/8kBMIL-4PZI?list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'post-video-slider' => [
        'name' => 'post-video-slider',
        'title' => __('Post Video Slider', 'zoloblocks-pro'),
        'categories' => ['postCategory'],
        'class' => '\ZoloPro\Blocks\PostVideoSlider',
        'status' => true,
        'is_pro' => true,
        'demo' => 'https://demo.zoloblocks.com/post-video-slider',
        'video' => 'https://www.youtube.com/watch?v=7BFUp6CmNM0',
    ],
    'lottie-image' => [
        'name' => 'lottie-image',
        'title' => __('Lottie Image', 'zoloblocks-pro'),
        'categories' => ['others'],
        'status' => true,
        'is_pro' => true,
        'demo' => 'https://demo.zoloblocks.com/lottie-image',
        'video' => 'https://www.youtube.com/watch?v=gGBLq63e_LA&t',
    ],
    'form' => [
        'name' => 'form',
        'title' => __('Form', 'zoloblocks'),
        'categories' => ['form'],
        'status' => true,
        'demo' => 'https://demo.zoloblocks.com/form',
        'video' => 'https://www.youtube.com/watch?v=fYpbDbMdlF0&list=PLP0S85GEw7DPpFyon1kxBZ8H1Ei7GK1yX',
    ],
    'number-field' => [
        'name' => 'number-field',
        'title' => __('Number Field', 'zoloblocks'),
        'categories' => ['form'],
        'status' => true,
        // 'is_child' => true,
    ],
    // 'datetime-field' => [
    //     'name' => 'datetime-field',
    //     'title' => __('Date Time Field', 'zoloblocks-pro'),
    //     'categories' => ['form'],
    //     'status' => true,
    //     'is_pro' => true,
    // ],
    'checkbox-field' => [
        'name' => 'checkbox-field',
        'title' => __('Checkbox Field', 'zoloblocks'),
        'categories' => ['form'],
        'status' => true,
        // 'is_child' => true,
    ],
    'phonenumber-field' => [
        'name' => 'phonenumber-field',
        'title' => __('Phone Number', 'zoloblocks-pro'),
        'categories' => ['form'],
        'status' => true,
        'is_pro' => true,
    ],
    'country-field' => [
        'name' => 'country-field',
        'title' => __('Country Field', 'zoloblocks-pro'),
        'categories' => ['form'],
        'status' => true,
        'is_pro' => true,
    ],
    'select-field' => [
        'name' => 'select-field',
        'title' => __('Select Field', 'zoloblocks'),
        'categories' => ['form'],
        'status' => true,
        // 'is_child' => true,
    ],
    'textarea' => [
        'name' => 'textarea',
        'title' => __('Textarea', 'zoloblocks'),
        'categories' => ['form'],
        'status' => true,
        // 'is_child' => true,
    ],
    'radio-field' => [
        'name' => 'radio-field',
        'title' => __('Radio Field', 'zoloblocks'),
        'categories' => ['form'],
        'status' => true,
        // 'is_child' => true,
    ],
    'email' => [
        'name' => 'email',
        'title' => __('Email', 'zoloblocks'),
        'categories' => ['form'],
        'status' => true,
        // 'is_child' => true,
    ],
    'text-field' => [
        'name' => 'text-field',
        'title' => __('Text Field', 'zoloblocks'),
        'categories' => ['form'],
        'status' => true,
        // 'is_child' => true,
    ],
]);
