<?php
return apply_filters('zolo_extensions', [
    'cursors'          => [
        'name'   => 'cursors',
        'title'  => __('Cursors Animation', 'zoloblocks'),
        'status' => false,
        'demo'   => 'https://zoloblocks.com',
        'is_pro' => true,
        'video'  => 'https://youtu.be/HPEVm1xGT3I?list=PLFnvpmjcONzLJMQiRFpLAxHsz-RSmZstT',
    ],
    'floating'          => [
        'name'   => 'floating',
        'title'  => __('Floating Animation', 'zoloblocks'),
        'status' => true,
        'demo'   => 'https://zoloblocks.com',
        'is_pro' => true,
        'video'  => 'https://youtu.be/HPEVm1xGT3I?list=PLFnvpmjcONzLJMQiRFpLAxHsz-RSmZstT',
    ],
    'entrance'          => [
        'name'   => 'entrance',
        'title'  => __('Entrance Animation', 'zoloblocks'),
        'status' => true,
        'demo'   => 'https://zoloblocks.com',
        'is_pro' => true,
        'video'  => 'https://youtu.be/HPEVm1xGT3I?list=PLFnvpmjcONzLJMQiRFpLAxHsz-RSmZstT',
    ],
    'sticky'          => [
        'name'   => 'sticky',
        'title'  => __('Sticky Position', 'zoloblocks'),
        'status' => true,
        'demo'   => 'https://zoloblocks.com',
        'is_pro' => true,
        'video'  => 'https://youtu.be/HPEVm1xGT3I?list=PLFnvpmjcONzLJMQiRFpLAxHsz-RSmZstT',
    ],
    'parallax'          => [
        'name'   => 'parallax',
        'title'  => __('Parallax Effect', 'zoloblocks'),
        'status' => true,
        'demo'   => 'https://zoloblocks.com',
        'is_pro' => true,
        'video'  => 'https://youtu.be/HPEVm1xGT3I?list=PLFnvpmjcONzLJMQiRFpLAxHsz-RSmZstT',
    ],
    'particles'          => [
        'name'   => 'particles',
        'title'  => __('Particles Animation', 'zoloblocks'),
        'status' => false,
        'demo'   => 'https://demo.zoloblocks.com/particles/',
        'video'  => 'https://youtu.be/HPEVm1xGT3I?list=PLFnvpmjcONzLJMQiRFpLAxHsz-RSmZstT',
    ],
    'tilt'          => [
        'name'   => 'tilt',
        'title'  => __('Mouse Tilt', 'zoloblocks'),
        'status' => false,
        'is_pro' => true,
        'demo'   => 'https://demo.zoloblocks.com/tilt',
        'video'  => 'https://youtu.be/HPEVm1xGT3I?list=PLFnvpmjcONzLJMQiRFpLAxHsz-RSmZstT',
    ],
    'smooth-scroller'          => [
        'name'   => 'smooth-scroller',
        'title'  => __('Smooth Scroller', 'zoloblocks'),
        'status' => false,
        'is_pro' => true,
        'demo'   => 'https://demo.zoloblocks.com/smooth-scroller',
        'video'  => 'https://youtu.be/v7zs3NxFnxc?list=PLFnvpmjcONzI5eoNTbMmjbpYQGdy_zsj8',
    ],
    'css-filters'          => [
        'name'   => 'css-filters',
        'title'  => __('CSS Filters', 'zoloblocks'),
        'status' => false,
        'is_pro' => true,
        'demo'   => 'https://demo.zoloblocks.com/css-filters',
        'video'  => 'https://youtu.be/FlwqbmhGyjs?list=PLFnvpmjcONzI5eoNTbMmjbpYQGdy_zsj8',
    ],
    'backdrop-filters'          => [
        'name'   => 'backdrop-filters',
        'title'  => __('Backdrop Filters', 'zoloblocks'),
        'status' => false,
        'is_pro' => true,
        'demo'   => 'https://demo.zoloblocks.com/backdrop-filters',
        'video'  => 'https://youtu.be/HPEVm1xGT3I?list=PLFnvpmjcONzLJMQiRFpLAxHsz-RSmZstT',
    ],

    'background-parallax'          => [
        'name'   => 'background-parallax',
        'title'  => __('Background Parallax', 'zoloblocks'),
        'status' => false,
        'is_pro' => true,
        'demo'   => 'https://demo.zoloblocks.com/background-parallax',
        'video'  => 'https://youtu.be/HPEVm1xGT3I?list=PLFnvpmjcONzLJMQiRFpLAxHsz-RSmZstT',
    ],
    'export-pattern'          => [
        'name'   => 'export-pattern',
        'title'  => __('Export Pattern', 'zoloblocks'),
        'status' => false,
        'demo'   => 'https://demo.zoloblocks.com/export-pattern',
        'video'  => 'https://youtu.be/HPEVm1xGT3I?list=PLFnvpmjcONzLJMQiRFpLAxHsz-RSmZstT',
    ],
    'import-pattern'          => [
        'name'   => 'import-pattern',
        'title'  => __('Import Pattern', 'zoloblocks'),
        'status' => false,
        'demo'   => 'https://demo.zoloblocks.com/import-pattern',
        'video'  => 'https://youtu.be/HPEVm1xGT3I?list=PLFnvpmjcONzLJMQiRFpLAxHsz-RSmZstT',
    ],
    'shape-divider'          => [
        'name'   => 'shape-divider',
        'title'  => __('Shape Divider', 'zoloblocks'),
        'status' => false,
        'demo'   => 'https://demo.zoloblocks.com/shape-divider',
        'video'  => 'https://youtu.be/OD3sI03RMDc?list=PLFnvpmjcONzI5eoNTbMmjbpYQGdy_zsj8',
    ],
    'AI'          => [
        'name'   => 'AI',
        'title'  => __('AI', 'zoloblocks'),
        'status' => false,
        'demo'   => 'https://demo.zoloblocks.com/ai',
        'video'  => 'https://youtu.be/OD3sI03RMDc?list=PLFnvpmjcONzI5eoNTbMmjbpYQGdy_zsj8',
    ],
    'dynamic-content'          => [
        'name'     => 'dynamic-content',
        'title'    => __('Dynamic Content', 'zoloblocks'),
        'status'   => false,
        'is_pro'   => true,
        'demo'     => 'https://demo.zoloblocks.com/dynamic-content',
        'video'    => 'https://youtu.be/HPEVm1xGT3I?list=PLFnvpmjcONzLJMQiRFpLAxHsz-RSmZstT',
    ],
    'interactions'          => [
        'name'   => 'interactions',
        'title'  => __('Interactions', 'zoloblocks'),
        'status' => false,
        'is_pro' => true,
        'demo'   => 'https://demo.zoloblocks.com/interactions',
        'video'  => 'https://youtu.be/FlwqbmhGyjs?list=PLFnvpmjcONzI5eoNTbMmjbpYQGdy_zsj8',
    ],
]);
