<?php
return apply_filters('zolo_extensions', [
    'cursors'          => [
        'name'   => 'cursors',
        'title'  => __('Cursors Animation', 'zoloblocks'),
        'status' => false,
        'demo'   => 'https://zoloblocks.com',
        'is_pro' => true,
        'video'  => 'https://www.youtube.com/watch?v=pTDoHVq4kHk',
    ],
    'floating'          => [
        'name'   => 'floating',
        'title'  => __('Floating Animation', 'zoloblocks'),
        'status' => true,
        'demo'   => 'https://demo.zoloblocks.com/floating-animation',
        'is_pro' => true,
        'video'  => 'https://www.youtube.com/watch?v=c2qO5acU2yw&t',
    ],
    'entrance'          => [
        'name'   => 'entrance',
        'title'  => __('Entrance Animation', 'zoloblocks'),
        'status' => true,
        'demo'   => 'https://demo.zoloblocks.com/entrance-animation',
        'is_pro' => true,
        'video'  => 'https://www.youtube.com/watch?v=3zPdiQ9SSHE&t',
    ],
    'sticky'          => [
        'name'   => 'sticky',
        'title'  => __('Sticky Position', 'zoloblocks'),
        'status' => true,
        'demo'   => 'https://demo.zoloblocks.com/sticky-position',
        'is_pro' => true,
        'video'  => 'https://www.youtube.com/watch?v=2VlVmMDQ-lM&t',
    ],
    'parallax'          => [
        'name'   => 'parallax',
        'title'  => __('Parallax Effect', 'zoloblocks'),
        'status' => true,
        'demo'   => 'https://demo.zoloblocks.com/scroll-parallax-animation',
        'is_pro' => true,
        'video'  => 'https://youtu.be/HPEVm1xGT3I?list=PLFnvpmjcONzLJMQiRFpLAxHsz-RSmZstT',
    ],
    'particles'          => [
        'name'   => 'particles',
        'title'  => __('Particles Animation', 'zoloblocks'),
        'status' => false,
        'demo'   => 'https://demo.zoloblocks.com/particles/',
        'video'  => 'https://youtu.be/HPEVm1xGT3I?list=PLFnvpmjcONzLJMQiRFpLAxHsz-RSmZstT',
    ],
    'tilt'          => [
        'name'   => 'tilt',
        'title'  => __('Mouse Tilt', 'zoloblocks'),
        'status' => false,
        'is_pro' => true,
        'demo'   => 'https://demo.zoloblocks.com/tilt-effects',
        'video'  => 'https://youtu.be/HPEVm1xGT3I?list=PLFnvpmjcONzLJMQiRFpLAxHsz-RSmZstT',
    ],
    'smooth-scroller'          => [
        'name'   => 'smooth-scroller',
        'title'  => __('Smooth Scroller', 'zoloblocks'),
        'status' => false,
        'is_pro' => true,
        'demo'   => 'https://demo.zoloblocks.com/smooth-scroller',
        'video'  => 'https://www.youtube.com/watch?v=6SlgnGtThNU',
    ],
    'css-filters'          => [
        'name'   => 'css-filters',
        'title'  => __('CSS Filters', 'zoloblocks'),
        'status' => false,
        'is_pro' => true,
        'demo'   => 'https://demo.zoloblocks.com/css-filters',
        'video'  => 'https://www.youtube.com/watch?v=FlwqbmhGyjs',
    ],
    'backdrop-filters'          => [
        'name'   => 'backdrop-filters',
        'title'  => __('Backdrop Filters', 'zoloblocks'),
        'status' => false,
        'is_pro' => true,
        'demo'   => 'https://demo.zoloblocks.com/backdrop-filters',
        'video'  => 'https://www.youtube.com/watch?v=8_oI0P3bj6w&t',
    ],
    'export-pattern'          => [
        'name'   => 'export-pattern',
        'title'  => __('Export Pattern', 'zoloblocks'),
        'status' => false,
        'demo'   => 'https://demo.zoloblocks.com/export-pattern',
        'video'  => 'https://youtu.be/HPEVm1xGT3I?list=PLFnvpmjcONzLJMQiRFpLAxHsz-RSmZstT',
    ],
    'import-pattern'          => [
        'name'   => 'import-pattern',
        'title'  => __('Import Pattern', 'zoloblocks'),
        'status' => false,
        'demo'   => 'https://demo.zoloblocks.com/import-pattern',
        'video'  => 'https://youtu.be/HPEVm1xGT3I?list=PLFnvpmjcONzLJMQiRFpLAxHsz-RSmZstT',
    ],
    'shape-divider'          => [
        'name'   => 'shape-divider',
        'title'  => __('Shape Divider', 'zoloblocks'),
        'status' => false,
        'demo'   => 'https://demo.zoloblocks.com/shape-divider',
        'video'  => 'https://www.youtube.com/watch?v=OD3sI03RMDc&t',
    ],
    'ai-assistant'          => [
        'name'   => 'ai-assistant',
        'title'  => __('AI Assistant', 'zoloblocks'),
        'status' => false,
        'demo'   => 'https://demo.zoloblocks.com/ai-assistant',
        'video'  => 'https://www.youtube.com/watch?v=-RAtIns09V8',
    ],
    'dynamic-content'          => [
        'name'     => 'dynamic-content',
        'title'    => __('Dynamic Content', 'zoloblocks'),
        'status'   => false,
        'is_pro'   => true,
        'demo'     => 'https://demo.zoloblocks.com/dynamic-content',
        'video'    => 'https://www.youtube.com/watch?v=oCFZ121wWlA',
    ],
    'interactions'          => [
        'name'   => 'interactions',
        'title'  => __('Interactions', 'zoloblocks'),
        'status' => false,
        'is_pro' => true,
        'demo'   => 'https://demo.zoloblocks.com/interactions',
        'video'  => 'https://youtu.be/HPEVm1xGT3I?list=PLFnvpmjcONzLJMQiRFpLAxHsz-RSmZstT',
    ],
    'text-animation'          => [
        'name'   => 'text-animation',
        'title'  => __('Text Animation', 'zoloblocks'),
        'status' => true,
        'is_pro' => true,
        'demo'   => 'https://demo.zoloblocks.com/interactions',
        'video'  => 'https://www.youtube.com/watch?v=gX_mALFBdIE&t',
    ],
    'display-condition'          => [
        'name'   => 'display-condition',
        'title'  => __('Display Condition', 'zoloblocks'),
        'status' => true,
        'is_pro' => true,
        'demo'   => 'https://demo.zoloblocks.com/display-condition',
        'video'  => 'https://youtu.be/HPEVm1xGT3I?list=PLFnvpmjcONzLJMQiRFpLAxHsz-RSmZstT',
    ],
    'tooltip' => [
        'name' => 'tooltip',
        'title' => __('Zolo Tooltip', 'zoloblocks'),
        'status' => true,
        'is_pro' => true,
        'demo' => 'https://demo.zoloblocks.com/tooltip',
        'video' => 'https://youtu.be/HPEVm1xGT3I?list=PLFnvpmjcONzLJMQiRFpLAxHsz-RSmZstT',
    ],
    'highlight' => [
        'name' => 'highlight',
        'title' => __('Zolo Highlight', 'zoloblocks'),
        'status' => true,
        'is_pro' => true,
        'demo' => 'https://demo.zoloblocks.com/highlight',
        'video' => 'https://www.youtube.com/watch?v=mMT88v_xQig&t',
    ]
]);
